# MPC parameters
state_costs:
  x: 20
  dx: 0.1
  z: 40
  dz: 40
  att: 20000
  datt: 2
  droll: 1

input_costs:
  servo: 3
  thrust: 0.1
  torque: 0.001

# constraints (+ used for scaling)
min_z: 0
min_dz: -3

max_dx: 1.2
max_dz: 20
max_datt: 0.6
max_attitude_angle: 90

# scaling
scaling_x: 2
scaling_z: 4


# speed/performance
horizon_length: 2

max_sqp_iter: 1
max_qp_iter: 25
max_line_search_iter: 4
mpc_period: 0.02
feedforward_period: 0.02

weight_scaling: 64