# MPC parameters
state_costs:
  x: 10
  dx: 0.1
  z: 500
  dz: 50
  att: 10
  datt: 5
  droll: 1

input_costs:
  servo: 5
  thrust: 0.01
  torque: 0.001

# constraints (+ used for scaling)
min_z: 0
min_dz: -0.6

max_dx: 1.2
max_dz: 20
max_datt: 0.6
max_attitude_angle: 90

# scaling
scaling_x: 2
scaling_z: 4


# speed/performance
horizon_length: 1.0

max_sqp_iter: 1
max_qp_iter: 25
max_line_search_iter: 4
mpc_period: 0.01666
feedforward_period: 0.01666

weight_scaling: 64