# MPC parameters
#state_costs:
#  x: 3
#  dx: 0.1
#  z: 5
#  dz: 30
#  att: 0.5
#  datt: 1
#  droll: 1
#
#input_costs:
#  servo: 5
#  thrust: 0.001
#  torque: 0.001

state_costs:
  x: 5
  dx: 0.1
  z: 20
  dz: 50
  att: 0.5
  datt: 1
  droll: 5

input_costs:
  servo: 5
  thrust: 0.01
  torque: 0.001

# constraints (+ used for scaling)
min_z: 0
min_dz: -1.5

max_dx: 1.2
max_dz: 20
max_datt: 0.6
max_attitude_angle: 90

# scaling
scaling_x: 2
scaling_z: 4


# speed/performance
horizon_length: 2.0

max_sqp_iter: 1
max_qp_iter: 25
max_line_search_iter: 4
mpc_period: 0.02
feedforward_period: 0.02

weight_scaling: 64