# Kalman filter parameters
predict_vars:
  x: 0.01
  att: 4

  dx: 5
  datt: 2000

  thrust_scaling: 0.1
  torque_scaling: 0.1
  servo_offset: 1.0e-10
  disturbance_force: 30
  disturbance_force_z: 1.0e-10
  disturbance_torque: 10
  disturbance_torque_z: 0.5

update_vars:
  optitrack_x: 0.01
  optitrack_att: 0.01
  pixhawk: 0.01

period: 0.01