# Kalman filter parameters
predict_vars:
  x: 0.01
  att: 4

  dx: 5
  datt: 2000

  thrust_scaling: 0.1
  torque_scaling: 0
  servo_offset: 1.0e-6
  disturbance_force: 0.1
  disturbance_force_z: 1.0e-6
  disturbance_torque: 0.01
  disturbance_torque_z: 0.5

update_vars:
  optitrack_x: 0.001
  optitrack_att: 0.001
  pixhawk: 0.001

period: 0.002