horizontal_slack: 30

max_attitude_angle: 45

descent_min_propeller_speed: 60

# constraints (+ used for scaling)
min_z: 0

min_dz: -1
max_dz: 5

max_horizon_length: 30.0

max_sqp_iter: 1
max_qp_iter: 1000
max_line_search_iter: 5