# MPC parameters
state_costs:
  x: 1
  dx: 0.1
  z: 5
  dz: 0.5

input_costs:
  servo: 50
  thrust: 0.01

# constraints (+ used for scaling)
min_z: -1
min_dz: -0.6

max_dx: 10
max_dz: 20

# scaling
scaling_x: 2
scaling_z: 4

# speed/performance
horizon_length: 30.0

max_sqp_iter: 3
max_qp_iter: 2000
max_line_search_iter: 5
mpc_period: 0.1

weight_scaling: 1