# MPC parameters
state_costs:
  x: 5.0e+1
  dx: 1.0e-3
  z: 5.0e+0
  dz: 1.0e+2
  att: 1.0e-2
  datt: 1.0e+0
  droll: 1.0e-2
input_costs:
  servo: 5.0e-2
  thrust: 1.0e-2
max_iter: 5
line_search_max_iter: 4