# Kalman filter parameters
predict_vars:
  x: 0.01
  att: 4

  dx: 5
  datt: 2000

  thrust_scaling: .6
  torque_scaling: 5
  servo_offset: 0
  disturbance_force: 40
  disturbance_force_z: 0
  disturbance_torque: 100
  disturbance_torque_z: 1

update_vars:
  optitrack_x: 0.001
  pixhawk: 0.001

period: 0.005