# Kalman filter parameters
predict_vars:
  x: 0.01
  att: 20

  dx: 30
  datt: 500

  thrust_scaling: 1
  torque_scaling: 1
  servo_offset: 0.03
  disturbance_force: 20
  disturbance_force_z: 0
  disturbance_torque: 100
  disturbance_torque_z: 4

update_vars:
  optitrack_x: 0.005
  optitrack_att: 0.005

period: 0.005