# Kalman filter parameters
predict_vars:
  x: 0.01
  att: 4

  dx: 5
  datt: 2000

  thrust_scaling: 0.3
  torque_scaling: 1
  servo_offset: 1.0e-6
  disturbance_force: 5
  disturbance_force_z: 1.0e-6
  disturbance_torque: 10
  disturbance_torque_z: 0.5

update_vars:
  optitrack_x: 0.001
  pixhawk: 0.001

period: 0.008