# MPC parameters
predict_vars:
  x: 0.5
  z: 0.5
  dx: 500
  dz: 500
  att: 0.05
  datt: 1000
  thrust_scaling: 0.3
  torque_scaling: 0.2
  servo_offset: 0.2
  disturbance_torque: 50
  disturbance_force: 0