# Kalman filter parameters
predict_vars:
  x: 0.01
  att: 4

  dx: 30
  datt: 600

  thrust_scaling: 1
  torque_scaling: 1
  servo_offset: 0.01
  disturbance_force: 20
  disturbance_force_z: 0
  disturbance_torque: 200
  disturbance_torque_z: 40

update_vars:
  optitrack_x: 0.005
  optitrack_att: 0.005

period: 0.005