# Drone parameters
stages: 4
diameters:
  - 0.26
  - 0.26
  - 0.26
  - 0.26
stage_z:
  - 0
  - 0.2
  - 0.3
  - 0.5
fin_n: 3
fin_top_offset: 0.25
fin_span: 1.0e-40
fin_root_chord: 0.1 # base length
fin_tip_chord: 0.1
fin_sweep: 0.1
fin_thickness: 0.004
lug_n: 2
lug_S: 1.0e-40
dry_mass: 1.67 # 1.67 without cover, +0.28 = 1.95 with cover
dry_CM: 0.215
dry_I:
  - 0.0644
  - 0.0644
  - 0.0128
propellant_mass: 1.0e-40
propellant_CM: 0.1
#set Isp to -1 for constant propellant mass
Isp: -1

CM_to_thrust_distance:  0.215
Cd:
  - 2
  - 2
  - 0.7
CM_offset_x: 0
initial_speed: 0

min_propeller_speed: 40
max_propeller_speed: 90

max_propeller_delta: 40

max_servo1_angle: 15
max_servo2_angle: 15

max_servo_rate: 100

estimated:
  thrust_scaling: 1.05 #1.05 when close to ground, else 1
  torque_scaling: 1
  servo1_offset: 0
  servo2_offset: 0